### ISSUE TITLE
User pre save

### ISSUE THREAD

**Issue by MisaZ10** [ivanhuay/generator-hiroki#2]
El user schema debería tener esto ?
`userSchema.pre('save', function (next) {
    let user = this;
    if (user.isModified('password')) {
        user.password = bcrypt.hashSync(user.password, bcrypt.genSaltSync(8), null);
    }
    return next();
});
`

**Comment by ivanhuay** [comment]
podría tenerlo o no. Es para la encripcion de la pass. Según recuerdo eso se agrega cuando elegís jwt en true.

**Comment by ivanhuay** [comment]
esta la corrección en la [ultima versión](https://github.com/ivanhuay/generator-hiroki/commit/253fa9766b95026ab3330ef1a5619aa72f6ab597)
