### ISSUE TITLE
Error to default public routes

### ISSUE THREAD

**Issue by MisaZ10** [ivanhuay/generator-hiroki#3]
I created a basic private api with this generator and I found a problem.

you use this defautl config (config/public.js)
`const publicPaths = ['login', 'signup'];`

but the right default config is this 
`const publicPaths = ['api/auth/login', 'api/auth/signup'];`

nice repo

**Comment by ivanhuay** [comment]
fix in [version  0.1.1 ](https://github.com/ivanhuay/generator-hiroki/commit/7297f3f58f0a106b0e77d5920ef8492a94f235a9)
